# exclude SafeMath when calculating test coverage
# https://eth-brownie.readthedocs.io/en/v1.10.3/config.html#exclude_paths
reports:
  exclude_contracts:
    - SafeMath
dependencies:
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
  - OpenZeppelin/openzeppelin-contracts@4.8.0
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.8.0'
# automatically fetch contract sources from Etherscan
autofetch_sources: True
dotenv: .env
# set a custom mnemonic for the development network
networks:
  default: development
  goerli:
    vrf_coordinator: "0x2Ca8E0C643bDe4C2E08ab1fA0da3401AdAD7734D" 
    link_token: "0x326C977E6efc84E512bB9C30f76E30c160eD06FB"
    keyhash: "0x79d3d8832d904592c0bf9818b621522c988bb8b0c05cdc3b15aea1b6e8db0c15"
    fee: 100000000000000000
    oracle: "0xCC79157eb46F5624204f47AB42b3906cAA40eaB7"
    jobId: ca98366cc7314957b8c012c72f05aeeb
    eth_usd_price_feed: "0xD4a33860578De61DBAbDc8BFdb98FD742fA7028e"
    link_eth_price_feed: "0xb4c4a493AB6356497713A78FFA6c60FB53517c63"
    weth_token: '0xB4FBF271143F4FBf7B91A5ded31805e42b2208d6' 